version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:4173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3001
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - app-network
    links:
      - "postgres:database"

  postgres:
    image: postgres:15-alpine
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
